# fly.toml app configuration file generated for tsb-resume on 2023-06-04T16:47:44+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tsb-resume"
primary_region = "iad"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = "suspend"
auto_start_machines = true
min_machines_running = 0
